### ISSUE TITLE
AttributeError: 'array.array' object has no attribute 'tostring' proposed fix

### ISSUE THREAD

**Issue by skoinks** [kevinhendricks/KindleUnpack#43]
Hello!

I was trying to convert a .mobi dictionary file intended for an Amazon Kindle, in order to make a dictionary file for my Kobo Nia. I tried to use this utility but was receiving the following error:

```
Conversion Log 

Input Path = "D:\Programs\Dict\bulgarian_dictionary.mobi"
Output Path = "D:\Programs\Dict"
Epub Output Type Set To: Auto-detect


Please Wait ...

Palm DB type: BOOKMOBI, 4064 sections.
Unpacking a Mobipocket 7 book...
Processing Mobipocket 7 section of book...
Mobi Version: 7
Codec: utf-8
Title: Bulgarian Dictionary
Palmdoc compression
Unpacking images, resources, fonts, etc
File contains kindlegen source archive, extracting as kindlegensrc.zip
File contains kindlegen build log, extracting as kindlegenbuild.log
Unpacking raw markup language
Write ncx
Info: Document contains orthographic index, handle as dictionary

Parsing metaInflIndexData

Parsing metaOrthIndex
orthIndexCount is 17
orth entry uses ordt2 lookup table of type  0
Read dictionary index data
Error: 'array.array' object has no attribute 'tostring'
Traceback (most recent call last):
  File "D:\Programs\Dict\KindleUnpack-083\KindleUnpack.pyw", line 370, in unpackEbook
    kindleunpack.unpackBook(infile, outdir, apnxfile, epubversion, use_hd, dodump=dump, dowriteraw=writeraw, dosplitcombos=splitcombos)
  File "D:\Programs\Dict\KindleUnpack-083\lib\kindleunpack.py", line 932, in unpackBook
    process_all_mobi_headers(files, apnxfile, sect, mhlst, K8Boundary, False, epubver, use_hd)
  File "D:\Programs\Dict\KindleUnpack-083\lib\kindleunpack.py", line 853, in process_all_mobi_headers
    processMobi7(mh, metadata, sect, files, rscnames)
  File "D:\Programs\Dict\KindleUnpack-083\lib\kindleunpack.py", line 630, in processMobi7
    positionMap = dictSupport(mh, sect).getPositionMap()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Dict\KindleUnpack-083\lib\mobi_dict.py", line 205, in getPositionMap
    inflectionGroups = self.getInflectionGroups(text, inflectionControlByteCount, inflectionTagTable,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Dict\KindleUnpack-083\lib\mobi_dict.py", line 288, in getInflectionGroups
    inflection = self.applyInflectionRule(mainEntry, data, offset+1, offset+1+textLength)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Dict\KindleUnpack-083\lib\mobi_dict.py", line 377, in applyInflectionRule
    return utf8_str(byteArray.tostring())
                    ^^^^^^^^^^^^^^^^^^
AttributeError: 'array.array' object has no attribute 'tostring'
```

I traced the error down to the mobi_dict.py file function, and replaced the .tostring() call with a .tobytes() and the conversion ran successfully.

I'm not a very gifted programmer, so I don't understand the full repercussions of what I did, but maybe you can judge if it would be something you'd like to implement. 

mobi dictionary used:

[bulgarian_dictionary.zip](https://github.com/kevinhendricks/KindleUnpack/files/10367054/bulgarian_dictionary.zip)

Running Python 3.11.1

Thanks for the hard work!

**Comment by kevinhendricks** [comment]
Yes, that looks like a reasonable change.  utf8str can take either a string or bytes.

I will make that change in KindleUnpack master tomorrow.

Thank you for your bug report and suggested fix.

**Comment by kevinhendricks** [comment]
For the record, this changed because python itself removed tostring() in python 3.9 or thereabouts.

See https://bugs.python.org/issue38916

**Comment by kevinhendricks** [comment]
Just because I forget things,  I have reopened this just until I push your fix to master and then I will close it.

**Comment by kevinhendricks** [comment]
Okay pushed a fix for this to master.  Thank you for your test case.  I had to modify your solution so that tostring() is used for Python 2.7.X while tobytes() is used for Python 3.X just to maintain old python 2.78 compatibility.
